# Cross-platform tests for 64-bit little-endian x86_64 and 
# 32-bit big-endian PowerPC.
name: Cross-platform tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1.20.0
        with:
          target: ${{ matrix.target }}
      - run: cargo test --verbose
